# Default initial positions for tm12s_soft_two_fingers's ros2_control fake system

initial_positions:
  gripper_planar_4: 0
  gripper_planar_5: 0
  joint_1: 0
  joint_2: 0
  joint_3: 0
  joint_4: 0
  joint_5: 0
  joint_6: 0